#!/usr/bin/env python3
"""Export PyTorch raw storage files as C float arrays.

PyTorch checkpoint archives store tensor payloads as raw storage files under a
directory such as ``model_fp32/data``. This script reads each file in that
directory as little-endian IEEE-754 float32 values and writes one C array per
file.
"""

from __future__ import annotations

import argparse
import math
import struct
import sys
from pathlib import Path


STORAGE_METADATA = {
    "0": {
        "names": ("transformer.wte.weight", "lm_head.weight"),
        "shape": (65, 8),
    },
    "1": {
        "names": ("transformer.wpe.weight",),
        "shape": (32, 8),
    },
    "2": {
        "names": ("transformer.h.0.ln_1.weight",),
        "shape": (8,),
    },
    "3": {
        "names": ("transformer.h.0.attn.c_attn.weight",),
        "shape": (24, 8),
    },
    "4": {
        "names": ("transformer.h.0.attn.c_proj.weight",),
        "shape": (8, 8),
    },
    "5": {
        "names": ("transformer.h.0.ln_2.weight",),
        "shape": (8,),
    },
    "6": {
        "names": ("transformer.h.0.mlp.c_fc.weight",),
        "shape": (32, 8),
    },
    "7": {
        "names": ("transformer.h.0.mlp.c_proj.weight",),
        "shape": (8, 32),
    },
    "8": {
        "names": ("transformer.ln_f.weight",),
        "shape": (8,),
    },
}


def c_identifier(name: str) -> str:
    chars = [ch if ch.isalnum() else "_" for ch in name]
    ident = "".join(chars).strip("_") or "storage"
    if ident[0].isdigit():
        ident = f"data_{ident}"
    return ident


def format_float(value: float) -> str:
    if math.isnan(value):
        return "NAN"
    if math.isinf(value):
        return "INFINITY" if value > 0 else "-INFINITY"
    return f"{value:.9g}f"


def read_float32_file(path: Path) -> list[float]:
    raw = path.read_bytes()
    if len(raw) % 4 != 0:
        raise ValueError(f"{path} is {len(raw)} bytes, not a multiple of 4")
    return [item[0] for item in struct.iter_unpack("<f", raw)]


def sorted_storage_files(data_dir: Path) -> list[Path]:
    skipped = sorted(path.name for path in data_dir.iterdir() if path.is_file() and not path.name.isdigit())
    for name in skipped:
        print(f"skipping non-storage file: {name}", file=sys.stderr)

    files = [path for path in data_dir.iterdir() if path.is_file() and path.name.isdigit()]
    return sorted(files, key=lambda path: int(path.name))


def storage_symbol(storage_file: Path, symbol_prefix: str) -> str:
    metadata = STORAGE_METADATA.get(storage_file.name)
    if metadata:
        return c_identifier("_and_".join(metadata["names"]))
    return c_identifier(f"{symbol_prefix}_{storage_file.name}")


def storage_comment(storage_file: Path, value_count: int) -> str:
    metadata = STORAGE_METADATA.get(storage_file.name)
    if metadata:
        meaning = " / ".join(metadata["names"])
        shape = "x".join(str(dim) for dim in metadata["shape"])
        return f"/* {storage_file.name}: {meaning}; shape {shape}; {value_count} float32 values */"
    return f"/* {storage_file.name}: {value_count} float32 values */"


def storage_shape(storage_file: Path, value_count: int) -> tuple[int, ...]:
    metadata = STORAGE_METADATA.get(storage_file.name)
    if metadata:
        shape = metadata["shape"]
        expected_count = math.prod(shape)
        if expected_count != value_count:
            raise ValueError(
                f"{storage_file} has {value_count} values, but shape {shape} expects {expected_count}"
            )
        return shape
    return (value_count,)


def c_dimensions(shape: tuple[int, ...]) -> str:
    return "".join(f"[{dim}]" for dim in shape)


def write_values(lines: list[str], values: list[float], shape: tuple[int, ...]) -> None:
    if len(shape) == 1:
        for index in range(0, len(values), 8):
            chunk = values[index : index + 8]
            lines.append("    " + ", ".join(format_float(value) for value in chunk) + ",")
        return

    if len(shape) == 2:
        rows, cols = shape
        for row in range(rows):
            start = row * cols
            row_values = values[start : start + cols]
            lines.append("    {" + ", ".join(format_float(value) for value in row_values) + "},")
        return

    raise NotImplementedError(f"only 1D and 2D arrays are supported, got shape {shape}")


def write_c_file(data_dir: Path, output_path: Path, symbol_prefix: str) -> None:
    storage_files = sorted_storage_files(data_dir)
    if not storage_files:
        raise ValueError(f"no storage files found in {data_dir}")

    lines: list[str] = [
        "/* Generated by scripts/export_tensor_data_to_c.py. */",
        "/* Source directory: " + str(data_dir) + " */",
        "#include <math.h>",
        "",
    ]

    for storage_file in storage_files:
        values = read_float32_file(storage_file)
        shape = storage_shape(storage_file, len(values))
        symbol = storage_symbol(storage_file, symbol_prefix)
        lines.append(storage_comment(storage_file, len(values)))
        lines.append(f"const float {symbol}{c_dimensions(shape)} = {{")

        write_values(lines, values, shape)
        lines.append("};")
        lines.append("")

    output_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Convert PyTorch raw float32 storage files into C float arrays."
    )
    parser.add_argument(
        "data_dir",
        type=Path,
        help="Directory containing numbered PyTorch storage files, e.g. model_fp32/data.",
    )
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=Path("model_fp32_data.c"),
        help="C file to write. Defaults to ./model_fp32_data.c.",
    )
    parser.add_argument(
        "--symbol-prefix",
        default="data",
        help="Prefix for generated C array names. Defaults to 'data'.",
    )
    args = parser.parse_args()

    data_dir = args.data_dir.expanduser().resolve()
    output_path = args.output.expanduser().resolve()

    if not data_dir.is_dir():
        raise NotADirectoryError(data_dir)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    write_c_file(data_dir, output_path, args.symbol_prefix)
    print(f"wrote {output_path}")


if __name__ == "__main__":
    main()
